# Generated by Django 4.0.8 on 2025-02-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_code_alter_course_credit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='summary_fr',
            new_name='summary_hi',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='title_fr',
            new_name='title_hi',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='summary_fr',
            new_name='summary_hi',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='title_fr',
            new_name='title_hi',
        ),
        migrations.RenameField(
            model_name='upload',
            old_name='title_fr',
            new_name='title_hi',
        ),
        migrations.RenameField(
            model_name='uploadvideo',
            old_name='summary_fr',
            new_name='summary_hi',
        ),
        migrations.RenameField(
            model_name='uploadvideo',
            old_name='title_fr',
            new_name='title_hi',
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third'), ('Fourth', 'Fourth'), ('Fifth', 'Fifth'), ('Sixth', 'Sixth'), ('Seventh', 'Seventh'), ('Eighth', 'Eighth')], max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1),
        ),
    ]
