# Generated by Django 4.0.8 on 2025-02-19 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_essayquestion_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_text_fr',
            new_name='choice_text_hi',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='content_fr',
            new_name='content_hi',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='explanation_fr',
            new_name='explanation_hi',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='description_fr',
            new_name='description_hi',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='title_fr',
            new_name='title_hi',
        ),
    ]
